// Customer-facing release and recovery copy. No business identity is invented.
export const releaseCopy = {
  en: {
    support: 'Support', privacyPolicy: 'Privacy', refundPolicy: 'Refunds',
    supportBody: 'For help, privacy or refund requests, contact us with your story reference or PayPal transaction reference. Do not send passwords, payment card details or private photos.',
    supportMissing: 'Customer support is not configured yet. Public checkout is unavailable.',
    privacyBody: 'Your story and media are private to this browser. We use PayPal for payment, OpenRouter for script direction and fal.ai for generation. Video output temporarily uses a provider bearer link before it is copied to private storage. Unpaid drafts expire after 24 hours. Source photos and intermediate content are deleted within 7 days; completed videos expire after 30 days. Necessary payment and unresolved reconciliation records are retained separately from creative content. Contact support for privacy requests.',
    refundBody: 'Refunds under this policy are available only when the paid video is not delivered. The refund is 50% of the captured amount, rounded up to the nearest cent. Contact support at support@example.com with your PayPal transaction reference. Payment and delivery status are reviewed and eligible refunds are handled manually. Deleting content does not issue a refund. This policy does not limit rights required by applicable law.',
    editUnpaid: 'Cancel checkout and edit', reselect: 'Your text is kept. Please select your photos again before checkout.',
    paymentCheck: 'Payment must be checked before editing this story. Return to your story or contact support.',
    unsavedLeave: 'You have unsaved changes. Leave this page? Selected photos will need to be selected again.',
    submissionUnknown: 'We could not confirm whether this step was saved. Your entries are still here. Check the saved status before retrying.',
    checkSaved: 'Check saved status', safeRetry: 'The saved status was checked. Review your entries and try again.',
    sessionError: 'Return to Talember using the browser where you started your story.',
    paymentMismatch: 'This PayPal return does not match your story. Open your saved story.',
    consentError: 'Choose 1–4 adults or pets and confirm permission to use their photos.',
    uploadError: 'The prepared upload could not be accepted. Choose 1–4 valid JPG or PNG photos (originals up to 50 MB each); this page prepares smaller copies. Prepared copies must be at most 5 MB each and 10 MB total.',
    unexpectedError: 'We could not complete that step. Your entries remain here. Check the saved status before retrying.',
  },
  ru: {
    support: 'Поддержка', privacyPolicy: 'Конфиденциальность', refundPolicy: 'Возвраты',
    supportBody: 'Для помощи, запросов о данных или возврате укажите номер истории или платежа PayPal. Не отправляйте пароли, данные карты или личные фотографии.',
    supportMissing: 'Поддержка ещё не настроена. Оплата для всех пользователей пока недоступна.',
    privacyBody: 'История и медиа доступны только в этом браузере. PayPal обрабатывает оплату, OpenRouter помогает составить сценарий, fal.ai создаёт изображения и видео. До копирования в закрытое хранилище видео временно доступно по ссылке провайдера. Неоплаченные черновики истекают через 24 часа. Исходные фото и промежуточные материалы удаляются в течение 7 дней, готовые видео — через 30 дней. Необходимые платёжные записи и незавершённые проверки хранятся отдельно. По вопросам данных обращайтесь в поддержку.',
    refundBody: 'По этой политике возврат доступен только если оплаченное видео не доставлено. Возврат составляет 50% списанной суммы с округлением вверх до цента. Напишите в поддержку на support@example.com и укажите номер платежа PayPal. Оплата и доставка проверяются, а подходящие возвраты обрабатываются вручную. Удаление данных не запускает возврат. Эта политика не ограничивает права, предусмотренные применимым законодательством.',
    editUnpaid: 'Отменить оплату и изменить', reselect: 'Текст сохранён. Перед оплатой выберите фотографии заново.',
    paymentCheck: 'Перед изменением нужно проверить платёж. Откройте историю или обратитесь в поддержку.',
    unsavedLeave: 'Есть несохранённые изменения. Покинуть страницу? Фотографии придётся выбрать заново.',
    submissionUnknown: 'Не удалось подтвердить сохранение. Введённые данные остались здесь. Перед повтором проверьте сохранённое состояние.',
    checkSaved: 'Проверить сохранение', safeRetry: 'Сохранённое состояние проверено. Проверьте данные и повторите попытку.',
    sessionError: 'Откройте Talember в браузере, где вы начали историю.',
    paymentMismatch: 'Этот возврат из PayPal не соответствует вашей истории. Откройте сохранённую историю.',
    consentError: 'Выберите 1–4 взрослых или питомцев и подтвердите разрешение на использование фото.',
    uploadError: 'Подготовленные файлы не приняты. Выберите 1–4 JPG или PNG (оригиналы до 50 МБ каждый); страница уменьшит их. Подготовленные копии: до 5 МБ каждая и 10 МБ всего.',
    unexpectedError: 'Не удалось завершить шаг. Данные остались здесь. Перед повтором проверьте сохранённое состояние.',
  },
  es: {
    support: 'Ayuda', privacyPolicy: 'Privacidad', refundPolicy: 'Reembolsos',
    supportBody: 'Para ayuda, solicitudes de privacidad o reembolso, incluye la referencia de tu historia o transacción de PayPal. No envíes contraseñas, datos de tarjetas ni fotos privadas.',
    supportMissing: 'La atención al cliente aún no está configurada. El pago público no está disponible.',
    privacyBody: 'Tu historia y tus archivos son privados para este navegador. Usamos PayPal para pagos, OpenRouter para el guion y fal.ai para generar contenido. El vídeo utiliza temporalmente un enlace del proveedor antes de copiarse al almacenamiento privado. Los borradores sin pagar caducan a las 24 horas. Las fotos originales y el contenido intermedio se eliminan en 7 días; los vídeos terminados, en 30 días. Los registros necesarios de pagos y conciliaciones pendientes se conservan por separado. Contacta con ayuda para solicitudes de privacidad.',
    refundBody: 'Esta política permite un reembolso solo cuando no se entrega el vídeo pagado. El reembolso es del 50 % del importe cobrado, redondeado hacia arriba al céntimo. Contacta con soporte en support@example.com e indica la referencia de tu transacción de PayPal. Se revisan el pago y la entrega y se procesan los reembolsos elegibles manualmente. Eliminar contenido no emite un reembolso. Esta política no limita los derechos exigidos por la legislación aplicable.',
    editUnpaid: 'Cancelar pago y editar', reselect: 'Tu texto se conserva. Selecciona de nuevo las fotos antes de pagar.',
    paymentCheck: 'Debemos comprobar el pago antes de editar. Abre tu historia o contacta con ayuda.',
    unsavedLeave: 'Tienes cambios sin guardar. ¿Salir? Tendrás que seleccionar las fotos de nuevo.',
    submissionUnknown: 'No pudimos confirmar si se guardó este paso. Tus datos siguen aquí. Comprueba el estado guardado antes de reintentar.',
    checkSaved: 'Comprobar estado guardado', safeRetry: 'Estado guardado comprobado. Revisa tus datos e inténtalo de nuevo.',
    sessionError: 'Abre Talember en el navegador donde comenzaste tu historia.',
    paymentMismatch: 'Este regreso de PayPal no corresponde a tu historia. Abre tu historia guardada.',
    consentError: 'Elige de 1 a 4 adultos o mascotas y confirma el permiso para usar sus fotos.',
    uploadError: 'No se aceptó la carga preparada. Elige de 1 a 4 JPG o PNG (originales de hasta 50 MB cada uno); esta página los reduce. Las copias preparadas deben tener hasta 5 MB cada una y 10 MB en total.',
    unexpectedError: 'No pudimos completar este paso. Tus datos siguen aquí. Comprueba el estado guardado antes de reintentar.',
  },
  he: {
    support: 'תמיכה', privacyPolicy: 'פרטיות', refundPolicy: 'החזרים',
    supportBody: 'לעזרה, בקשות פרטיות או החזר, ציינו את מזהה הסיפור או עסקת PayPal. אין לשלוח סיסמאות, פרטי כרטיס או תמונות פרטיות.',
    supportMissing: 'שירות התמיכה עדיין לא הוגדר. התשלום לציבור אינו זמין.',
    privacyBody: 'הסיפור והמדיה פרטיים לדפדפן הזה. PayPal משמש לתשלום, OpenRouter להכנת התסריט ו־fal.ai ליצירה. הסרטון משתמש זמנית בקישור של הספק לפני העתקתו לאחסון פרטי. טיוטות שלא שולמו פגות לאחר 24 שעות. תמונות מקור ותוכן ביניים נמחקים בתוך 7 ימים; סרטונים מוכנים לאחר 30 ימים. רישומי תשלום נחוצים ובירורים פתוחים נשמרים בנפרד מהתוכן. לבקשות פרטיות פנו לתמיכה.',
    refundBody: 'לפי מדיניות זו, החזר ניתן רק אם הסרטון ששולם עבורו לא נמסר. ההחזר הוא 50% מהסכום שנגבה, בעיגול כלפי מעלה לסנט הקרוב. פנו לתמיכה בכתובת support@example.com עם מזהה עסקת PayPal. התשלום והמסירה נבדקים והחזרים זכאים מטופלים באופן ידני. מחיקת תוכן אינה מפעילה החזר. מדיניות זו אינה מגבילה זכויות הנדרשות לפי הדין החל.',
    editUnpaid: 'ביטול התשלום ועריכה', reselect: 'הטקסט נשמר. בחרו שוב את התמונות לפני התשלום.',
    paymentCheck: 'יש לבדוק את התשלום לפני עריכה. פתחו את הסיפור או פנו לתמיכה.',
    unsavedLeave: 'יש שינויים שלא נשמרו. לצאת מהעמוד? יהיה צורך לבחור שוב את התמונות.',
    submissionUnknown: 'לא ניתן לאשר שהשלב נשמר. הפרטים עדיין כאן. בדקו את המצב השמור לפני ניסיון נוסף.',
    checkSaved: 'בדיקת המצב השמור', safeRetry: 'המצב השמור נבדק. בדקו את הפרטים ונסו שוב.',
    sessionError: 'פתחו את Talember בדפדפן שבו התחלתם את הסיפור.',
    paymentMismatch: 'החזרה הזו מ־PayPal אינה תואמת לסיפור. פתחו את הסיפור השמור.',
    consentError: 'בחרו 1–4 מבוגרים או חיות מחמד ואשרו הרשאה לשימוש בתמונות.',
    uploadError: 'הקבצים המוכנים לא התקבלו. בחרו 1–4 תמונות JPG או PNG, עד 50 MB לכל מקור; העמוד יקטין אותן. העותקים המוכנים מוגבלים ל־5 MB כל אחד ול־10 MB בסך הכול.',
    unexpectedError: 'לא ניתן להשלים את השלב. הפרטים עדיין כאן. בדקו את המצב השמור לפני ניסיון נוסף.',
  },
};
